language: node_js
node_js:
    - "5"
    - "6"
    - "7"
script: npm test
notifications:
    email:
        recipients:
            - zlatkofedor@cherrysro.com
        on_success: change
        on_failure: always
services:
  - mongodb
